image: python:3.8-slim

stages:
  - lint
  - build
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

workflow:
  rules:
    # Run pipeline MR
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Remove pipeline branch if MR open
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    # Run pipeline branch
    - if: $CI_COMMIT_BRANCH
    # Run pipeline for tags
    - if: $CI_COMMIT_TAG

code_style:
  stage: lint
  before_script:
    - python --version
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install .
  script:
    - pycodestyle cosmian_secure_computation_client/

doc_style:
  stage: lint
  before_script:
    - python --version
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install .
  script:
    - pycodestyle cosmian_secure_computation_client/

static_analysis:
  stage: lint
  before_script:
    - python --version
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install .
  script:
    - pylint --rcfile=setup.cfg cosmian_secure_computation_client/

type_check:
  stage: lint
  before_script:
    - python --version
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install .
  script:
    - mypy cosmian_secure_computation_client/
  allow_failure: true

doc:
  stage: build
  before_script:
    - python --version
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements-dev.txt
  script:
    - sphinx-build docs docs/_build -E -a -W
    - mkdir html/ && mv docs/_build/* html/
  artifacts:
    name: "documentation"
    paths:
      - html/
    expire_in: 1 mos

release_wheel:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+(\.\d+)?([\.\-\_])?((a(lpha)?|b(eta)?|c|r(c|ev)?|pre(view)?)\d*)?(\.?(post|dev)\d*)?$/
  before_script:
    - python --version
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install build twine
  script:
    - |
      if [ "$(python setup.py --version)" == "$CI_COMMIT_TAG" ]
      then
          python -m build --wheel && twine upload -u "${PYPI_USERNAME}" -p "${PYPI_PASSWORD}" dist/*
      else
          echo "Git tag version should be the same as in setup.py!"
          exit 1
      fi
  artifacts:
    paths:
      - dist/*.whl

test_e2e_dev:
  image: gitlab.cosmian.com:5000/core/secure-computation-e2e:master
  stage: test
  rules:
    # Don't run on branch master and tags
    - if: $CI_COMMIT_BRANCH == 'master' || $CI_COMMIT_TAG
      when: never
    # Don't run on MR targeting master
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
      when: never
    # Otherwise, run
    - when: always
  variables:
    BACKEND_BRANCH: develop
    ENCLAVE_IMAGE: enclave-http_test:latest
    PYTHON_CLIENT_BRANCH: $CI_COMMIT_REF_NAME
  tags: [sgx]
  script:
    - secure_computation_e2e

test_e2e_prod:
  image: gitlab.cosmian.com:5000/core/secure-computation-e2e:master
  stage: test
  rules:
    # Run on MR targeting master
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
      allow_failure: false
    # Manual on other MR
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != 'master'
      when: manual
      allow_failure: true
  variables:
    BACKEND_BRANCH: main
    ENCLAVE_IMAGE: enclave-http:latest
    PYTHON_CLIENT_BRANCH: $CI_COMMIT_REF_NAME
  tags: [sgx]
  script:
    - secure_computation_e2e
