stages:
  - test

test_e2e_dev:
  image: gitlab.cosmian.com:5000/core/secure-computation-e2e:master
  stage: test
  variables:
    BACKEND_BRANCH: develop
    ENCLAVE_IMAGE: enclave-http_test:latest
    PYTHON_CLIENT_BRANCH: $CI_COMMIT_REF_NAME
  tags: [sgx]
  script:
    - secure_computation_e2e

test_e2e_prod:
  image: gitlab.cosmian.com:5000/core/secure-computation-e2e:master
  stage: test
  allow_failure: true
  variables:
    BACKEND_BRANCH: main
    ENCLAVE_IMAGE: enclave-http:latest
    PYTHON_CLIENT_BRANCH: $CI_COMMIT_REF_NAME
  tags: [sgx]
  script:
    - secure_computation_e2e